name: rvc
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.05.30=haa95532_0
  - certifi=2023.5.7=py310haa95532_0
  - cffi=1.15.1=py310h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=39.0.1=py310h21b164f_2
  - cuda-cccl=12.1.109=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=11.8.0=hd77b12b_0
  - filelock=3.9.0=py310haa95532_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - idna=3.4=py310haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - jinja2=3.1.2=py310haa95532_0
  - jpeg=9e=h2bbff1b_1
  - lerc=3.0=hd77b12b_0
  - libcublas=11.10.3.66=0
  - libcublas-dev=11.10.3.66=0
  - libcufft=10.7.2.124=0
  - libcufft-dev=10.7.2.124=0
  - libcurand=10.3.2.106=0
  - libcurand-dev=10.3.2.106=0
  - libcusolver=11.4.0.1=0
  - libcusolver-dev=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libcusparse-dev=11.7.4.91=0
  - libdeflate=1.17=h2bbff1b_0
  - libffi=3.4.4=hd77b12b_0
  - libnpp=11.7.4.75=0
  - libnpp-dev=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libnvjpeg-dev=11.8.0.2=0
  - libpng=1.6.39=h8cc25b3_0
  - libtiff=4.5.0=h6c2663c_2
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.1=py310h2bbff1b_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - mpmath=1.2.1=py310haa95532_0
  - networkx=2.8.4=py310haa95532_1
  - openssl=3.0.9=h2bbff1b_0
  - pillow=9.4.0=py310hd77b12b_0
  - pip=22.2.2=py310haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.11=he1021f5_3
  - pytorch-cuda=11.7=h16d0643_5
  - pytorch-mutex=1.0=cuda
  - requests=2.29.0=py310haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h2bbff1b_0
  - sympy=1.11.1=py310haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - urllib3=1.26.16=py310haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - absl-py==1.4.0
      - accelerate==0.20.3
      - aiofiles==23.2.1
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - albumentations==1.1.0
      - altair==5.2.0
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.8
      - anyio==3.7.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - audioread==3.0.1
      - av==11.0.0
      - beautifulsoup4==4.12.3
      - bitarray==2.8.5
      - browser-cookie3==0.19.1
      - bs4==0.0.2
      - cachetools==5.3.1
      - captionizer==1.0.1
      - click==8.1.7
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - comtypes==1.4.2
      - contourpy==1.2.0
      - csv-logger==1.3.0
      - cycler==0.12.1
      - cython==3.0.6
      - datasets==2.13.0
      - decorator==5.1.1
      - diffusers==0.3.0
      - dill==0.3.6
      - einops==0.4.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.0
      - fairseq==0.12.2
      - faiss-cpu==1.7.3
      - fastapi==0.88.0
      - ffmpeg-python==0.2.0
      - ffmpy==0.3.1
      - flatbuffers==23.5.26
      - fonttools==4.44.0
      - frozenlist==1.3.3
      - fsspec==2023.6.0
      - ftfy==6.1.1
      - future==0.18.3
      - google-auth==2.20.0
      - google-auth-oauthlib==1.0.0
      - gradio==3.34.0
      - gradio-client==0.7.3
      - grpcio==1.54.2
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.25.2
      - huggingface-hub==0.19.4
      - humanfriendly==10.0
      - hydra-core==1.0.7
      - imageio==2.31.1
      - importlib-metadata==6.7.0
      - joblib==1.2.0
      - json5==0.9.14
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - keyboard==0.13.5
      - kiwisolver==1.4.5
      - kornia==0.6.7
      - lazy-loader==0.2
      - librosa==0.9.1
      - linkify-it-py==2.0.2
      - llvmlite==0.39.0
      - lxml==4.9.3
      - lz4==4.3.3
      - markdown==3.4.3
      - markdown-it-py==2.2.0
      - matplotlib==3.8.1
      - matplotlib-inline==0.1.6
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - modelcards==0.1.6
      - mouseinfo==0.1.3
      - msgpack==1.0.7
      - multidict==6.0.4
      - multiprocess==0.70.14
      - numba==0.56.4
      - numpy==1.23.5
      - oauthlib==3.2.2
      - omegaconf==2.0.6
      - onnxruntime-gpu==1.16.3
      - opencv-python==4.7.0.72
      - opencv-python-headless==4.7.0.72
      - openpyxl==3.1.5
      - orjson==3.9.10
      - packaging==23.1
      - pandas==2.0.2
      - platformdirs==4.1.0
      - pooch==1.8.0
      - portalocker==2.8.2
      - praat-parselmouth==0.4.3
      - protobuf==4.23.3
      - psutil==5.9.5
      - pyarrow==12.0.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyautogui==0.9.54
      - pycryptodomex==3.21.0
      - pydantic==1.10.13
      - pydantic-core==2.14.5
      - pydeprecate==0.3.2
      - pydub==0.25.1
      - pygetwindow==0.0.9
      - pygments==2.17.2
      - pymsgbox==1.0.9
      - pynput==1.7.7
      - pyparsing==3.1.1
      - pyperclip==1.8.2
      - pypower==5.1.16
      - pyreadline3==3.4.1
      - pyrect==0.2.0
      - pyscreeze==0.1.30
      - python-dateutil==2.8.2
      - python-docx==1.1.2
      - python-dotenv==1.0.0
      - python-graphviz==0.20.3
      - python-multipart==0.0.6
      - pytorch-lightning==1.7.6
      - pytweening==1.2.0
      - pytz==2023.3
      - pywavelets==1.4.1
      - pywin32==306
      - pywinauto==0.6.8
      - pyworld==0.3.2
      - pyyaml==6.0
      - qudida==0.0.4
      - referencing==0.32.0
      - regex==2023.6.3
      - requests-oauthlib==1.3.1
      - resampy==0.4.2
      - rpds-py==0.13.2
      - rsa==4.9
      - sacrebleu==2.4.0
      - scikit-image==0.21.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - semantic-version==2.10.0
      - setuptools==68.0.0
      - sniffio==1.3.0
      - soundfile==0.12.1
      - soupsieve==2.6
      - soxr==0.3.7
      - starlette==0.22.0
      - tabulate==0.9.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - tokenizers==0.13.3
      - toolz==0.12.0
      - torch==2.0.1+cu118
      - torch-fidelity==0.3.0
      - torchaudio==2.0.2+cu118
      - torchcrepe==0.0.20
      - torchmetrics==0.11.1
      - torchvision==0.15.2+cu118
      - tornado==6.4
      - tqdm==4.65.0
      - traitlets==5.14.0
      - transformers==4.25.1
      - typing-extensions==4.9.0
      - tzdata==2023.3
      - uc-micro-py==1.0.2
      - uvicorn==0.24.0.post1
      - wcwidth==0.2.6
      - websockets==11.0.3
      - werkzeug==2.3.6
      - xxhash==3.2.0
      - yarl==1.9.2
      - zipp==3.15.0
